#!/bin/ksh

BNIMBLE_VERSION=$1

BN="/etc/rc.bNimble"
EXIT_NO=0

if [ ! -e $BN ]; then
	echo "Missing /etc/rc.bNimble"
	EXIT_NO=1
fi

if [ ! -d /opt/IBM/${BNIMBLE_VERSION}/lib ]; then
        echo "Missing base $BNIMBLE_VERSION code"
        EXIT_NO=1
fi

exit $EXIT_NO
